name: carbon_app_copy
description: A cabon copy app to simulate the way the app is.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  local_auth: ^2.1.2
  otp_text_field: ^1.1.3
  intl_phone_field: ^3.1.0
  intl: ^0.17.0
  percent_indicator: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0





flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
